name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    env:
      NUGET_KEY: ${{secrets.NUGET_KEY}}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.101
        
    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Run Tests
      run: dotnet test

    - name: Publish nuget packages
      uses: rohith/publish-nuget@v2.2.0
      with:
        PROJECT_FILE_PATH: TelSearchApi\TelSearchApi.csproj
